# Import Module

In [1]:
import pandas as pd
import numpy as np
import json

# Import technical Data

In [2]:
df = pd.read_hdf("technical500.h5", "data")
#df.index = pd.to_datetime(df.index, format='%Y-%m-%d')
#df.dropna(axis=0, inplace=True)
df.head()

,Open,High,Low,Close,Adj Close,Volume,lrets,MACD,stochastics,ATR
Date,,,,,,,,,,
1990-01-04,358.760010,358.760010,352.890015,355.670013,355.670013,177000000,-0.008650,0.000000,NaN,5.869995
1990-01-05,355.670013,355.670013,351.350006,352.200012,352.200012,158530000,-0.009804,-0.036878,NaN,4.320007
1990-01-08,352.200012,354.239990,350.540009,353.790009,353.790009,140110000,0.004504,-0.005628,NaN,3.699981
1990-01-10,349.619995,349.619995,344.320007,347.309998,347.309998,175990000,-0.006629,-0.160033,NaN,9.470002
1990-01-11,347.309998,350.140015,347.309998,348.529999,348.529999,154390000,0.003507,-0.170328,NaN,2.830017

# Import News data and convert it from Json to pandas dataframe

In [3]:
def open_json(year, month):
    "Save as pandas dataframe"
    file_str = 'data/' + str(year) + '-' + '{:02}'.format(month) + '.json'
    with open(file_str) as data_file:    
        NYTimes_data = json.load(data_file)
    
    date_list = []
    df = pd.DataFrame()  
    df['News'] = None
    

    for i in range(len(NYTimes_data["response"]["docs"][:])):
        if NYTimes_data["response"]["docs"][i]["pub_date"][:10] not in df.index:
            df.loc[NYTimes_data["response"]["docs"][i]["pub_date"][:10]] = NYTimes_data["response"]["docs"][:][i]['headline']['main']
        else:
            df.loc[NYTimes_data["response"]["docs"][i]["pub_date"][:10]] = df.loc[NYTimes_data["response"]["docs"][i]["pub_date"][:10]].values + NYTimes_data["response"]["docs"][:][i]['headline']['main']
    
    df.index = pd.to_datetime(df.index, format='%Y-%m-%d')
    df.sort_index(inplace=True)
    
    return df

# Merge technical data with News

In [4]:
def merge_news_price(df):
    all_news = pd.DataFrame()
    for i in range(1990, 2019):
        for j in range(1, 13):
            try:
                temp = open_json(i, j)
                all_news = all_news.append(temp)
                print("Completed {}-{}".format(i, j))
            except:
                pass
            
    all_news = pd.concat([df, all_news], axis=1)
    
    return all_news

In [5]:
data = merge_news_price(df)

Completed 1990-1
Completed 1990-2
Completed 1990-3
Completed 1990-4
Completed 1990-5
Completed 1990-6
Completed 1990-7
Completed 1990-8
Completed 1990-9
Completed 1990-10
Completed 1990-11
Completed 1990-12
Completed 1991-1
Completed 1991-2
Completed 1991-3
Completed 1991-4
Completed 1991-5
Completed 1991-6
Completed 1991-7
Completed 1991-8
Completed 1991-9
Completed 1991-10
Completed 1991-11
Completed 1991-12
Completed 1992-1
Completed 1992-2
Completed 1992-3
Completed 1992-4
Completed 1992-5
Completed 1992-6
Completed 1992-7
Completed 1992-8
Completed 1992-9
Completed 1992-10
Completed 1992-11
Completed 1992-12
Completed 1993-1
Completed 1993-2
Completed 1993-3
Completed 1993-4
Completed 1993-5
Completed 1993-6
Completed 1993-7
Completed 1993-8
Completed 1993-9
Completed 1993-10
Completed 1993-11
Completed 1993-12
Completed 1994-1
Completed 1994-2
Completed 1994-3
Completed 1994-4
Completed 1994-5
Completed 1994-6
Completed 1994-7
Completed 1994-8
Completed 1994-9
Completed 1994-10
Completed 1994-11
Completed 1994-12
Completed 1995-1
Completed 1995-2
Completed 1995-3
Completed 1995-4
Completed 1995-5
Completed 1995-6
Completed 1995-7
Completed 1995-8
Completed 1995-9
Completed 1995-10
Completed 1995-11
Completed 1995-12
Completed 1996-1
Completed 1996-2
Completed 1996-3
Completed 1996-4
Completed 1996-5
Completed 1996-6
Completed 1996-7
Completed 1996-8
Completed 1996-9
Completed 1996-10
Completed 1996-11
Completed 1996-12
Completed 1997-1
Completed 1997-2
Completed 1997-3
Completed 1997-4
Completed 1997-5
Completed 1997-6
Completed 1997-7
Completed 1997-8
Completed 1997-9
Completed 1997-10
Completed 1997-11
Completed 1997-12
Completed 1998-1
Completed 1998-2
Completed 1998-3
Completed 1998-4
Completed 1998-5
Completed 1998-6
Completed 1998-7
Completed 1998-8
Completed 1998-9
Completed 1998-10
Completed 1998-11
Completed 1998-12
Completed 1999-1
Completed 1999-2
Completed 1999-3
Completed 1999-4
Completed 1999-5
Completed 1999-6
Completed 1999-7
Completed 1999-8
Completed 1999-9
Completed 1999-10
Completed 1999-11
Completed 1999-12
Completed 2000-1
Completed 2000-2
Completed 2000-3
Completed 2000-4
Completed 2000-5
Completed 2000-6
Completed 2000-7
Completed 2000-8
Completed 2000-9
Completed 2000-10
Completed 2000-11
Completed 2000-12
Completed 2001-1
Completed 2001-2
Completed 2001-3
Completed 2001-4
Completed 2001-5
Completed 2001-6
Completed 2001-7
Completed 2001-8
Completed 2001-9
Completed 2001-10
Completed 2001-11
Completed 2001-12
Completed 2002-1
Completed 2002-2
Completed 2002-3
Completed 2002-4
Completed 2002-5
Completed 2002-6
Completed 2002-7
Completed 2002-8
Completed 2002-9
Completed 2002-10
Completed 2002-11
Completed 2002-12
Completed 2003-1
Completed 2003-2
Completed 2003-3
Completed 2003-4
Completed 2003-5
Completed 2003-6
Completed 2003-7
Completed 2003-8
Completed 2003-9
Completed 2003-10
Completed 2003-11
Completed 2003-12
Completed 2004-1
Completed 2004-2
Completed 2004-3
Completed 2004-4
Completed 2004-5
Completed 2004-6
Completed 2004-7
Completed 2004-8
Completed 2004-9
Completed 2004-10
Completed 2004-11
Completed 2004-12
Completed 2005-1
Completed 2005-2
Completed 2005-3
Completed 2005-4
Completed 2005-5
Completed 2005-6
Completed 2005-7
Completed 2005-8
Completed 2005-9
Completed 2005-10
Completed 2005-11
Completed 2005-12
Completed 2007-12
Completed 2008-1
Completed 2008-2
Completed 2008-3
Completed 2008-4
Completed 2008-5
Completed 2008-6
Completed 2008-7
Completed 2008-8
Completed 2008-9
Completed 2008-10
Completed 2009-1
Completed 2009-2
Completed 2009-4
Completed 2009-7
Completed 2009-8
Completed 2009-9
Completed 2009-10
Completed 2009-11
Completed 2009-12
Completed 2010-1
Completed 2010-2
Completed 2010-5
Completed 2010-6
Completed 2010-7
Completed 2010-8
Completed 2010-9
Completed 2010-10
Completed 2010-11
Completed 2010-12
Completed 2011-1
Completed 2011-2
Completed 2011-3
Completed 2011-4
Completed 2011-5
Completed 2011-6
Completed 2011-7
Completed 2011-8
Completed 2011-9
Completed 2011-10
Completed 2011-11
Completed 2012-1
Completed 2012-3
Completed 2012-4
Completed 2012-5
Completed 2012-6
Completed 2012-7
Completed 2012-8
Completed 2012-9
Completed 2012-10
Completed 2012-11
Completed 2012-12
Completed 2013-1
Completed 2013-4
Completed 2013-5
Completed 2013-6
Completed 2013-7
Completed 2013-8
Completed 2013-9
Completed 2013-10
Completed 2013-11
Completed 2013-12
Completed 2014-1
Completed 2014-2
Completed 2014-3
Completed 2014-4
Completed 2014-5
Completed 2014-6
Completed 2014-7
Completed 2014-9
Completed 2014-10
Completed 2014-11
Completed 2014-12
Completed 2015-1
Completed 2015-2
Completed 2015-3
Completed 2015-4
Completed 2015-5
Completed 2015-6
Completed 2015-7
Completed 2015-8
Completed 2015-9
Completed 2015-10
Completed 2015-11
Completed 2015-12
Completed 2016-1
Completed 2016-2
Completed 2016-3
Completed 2016-4
Completed 2016-5
Completed 2016-6
Completed 2016-7
Completed 2016-8
Completed 2016-9
Completed 2016-10
Completed 2016-11
Completed 2016-12
Completed 2017-1
Completed 2017-2
Completed 2017-3
Completed 2017-4
Completed 2017-5
Completed 2017-6
Completed 2017-7
Completed 2017-8
Completed 2017-9
Completed 2017-10
Completed 2017-11
Completed 2017-12
Completed 2018-1
Completed 2018-2
Completed 2018-3
Completed 2018-4
Completed 2018-5
Completed 2018-6
Completed 2018-7
Completed 2018-8
Completed 2018-9
Completed 2018-10

In [6]:
data.tail(30)

,Open,High,Low,Close,Adj Close,Volume,lrets,MACD,stochastics,ATR,News
2018-09-12,2888.290039,2894.649902,2879.199951,2888.919922,2888.919922,3.264930e+09,0.000357,-3.785216,55.976006,15.449951,Residents Prepare for Hurricane FlorenceEdgy I...
2018-09-13,2896.850098,2906.760010,2896.389893,2904.179932,2904.179932,3.254930e+09,0.005268,-3.030618,82.719774,17.840088,Stand. Run. And Run Some More.U.S. Aid Program...
2018-09-14,2906.379883,2908.300049,2895.770020,2904.979980,2904.979980,3.149800e+09,0.000275,-2.576736,84.121890,12.530029,The Playlist: Lana Del Rey’s Smoldering Return...
2018-09-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Companies Are Pushing for Less Disclosure. Is ...
2018-09-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Katharine Verville, Edward GottfriedNina Sudar..."
2018-09-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emmys Red Carpet Photos 2018Fatal Shark Attack...
2018-09-18,2890.739990,2911.169922,2890.429932,2904.310059,2904.310059,3.074610e+09,0.005355,-2.451980,77.030322,20.739990,"The Emmys Joked About TV’s Lack of Diversity, ..."
2018-09-19,2906.600098,2912.360107,2903.820068,2907.949951,2907.949951,3.280020e+09,0.001252,-2.251064,85.623058,8.540039,What’s on TV Wednesday: ‘The Greatest Showman’...
2018-09-20,2919.729980,2934.800049,2919.729980,2930.750000,2930.750000,3.337730e+09,0.007810,-0.624690,100.000000,26.850098,Household ChoresOn Politics: Stalemate Over Ka...
2018-09-21,2936.760010,2940.909912,2927.110107,2929.669922,2929.669922,5.607610e+09,-0.000369,0.241159,98.171531,13.799805,What’s on TV Friday: ‘Quincy’ and ‘Jack White:...
2018-09-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Why Does the Tennis Season End Before It’s Ove...
2018-09-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,‘America First’ Has WonKavanaugh Was Supposed ...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3.372210e+09,-0.003522,-0.119090,80.734942,17.040039,The Trouble With South Sudan’s New Peace DealC...
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3.285480e+09,-0.001306,-0.866335,74.284876,10.250000,"Corrections: September 25, 2018Do You Want You..."
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3.388620e+09,-0.003295,-2.276606,58.049771,27.869873,Braves Jump on Mets’ Bullpen for Sixth Straigh...
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3.060850e+09,0.002759,-2.841769,71.643845,21.250000,‘I Could Be Doing This All Day.’ Trump Delight...
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3.432300e+09,-0.000007,-3.367701,68.724388,13.030029,Tu resumen de noticias del viernesSyphilis Ris...
2018-09-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Corrections: September 29, 2018How to Know if ..."
2018-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Katherine Whitman, Frank Broomell Jr.Rose Scha..."
2018-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,How to win your first three months on the jobI...
2018-10-02,2923.800049,2931.419922,2919.370117,2923.429932,2923.429932,3.401880e+09,-0.000397,-3.165455,82.921023,17.439942,Jason Kander Withdraws From Kansas City Mayora...
2018-10-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,On Politics: Trump Empire Was Built On Suspect...
2018-10-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,My Human DoctorT’s Best Photos From Paris Fash...
2018-10-05,2902.540039,2909.639893,2869.290039,2885.570068,2885.570068,3.328980e+09,-0.005543,-5.849199,0.000000,54.139893,Protesters Pack the Senate BuildingT Suggests:...
2018-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F.B.I. Review of Kavanaugh Was Limited From th...
2018-10-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Amelia Sanchez-Moran, Nicholas AlexsovichBD Wo..."
2018-10-08,2877.530029,2889.449951,2862.080078,2884.429932,2884.429932,3.330320e+09,-0.000395,-7.839346,0.000000,27.369873,New U.N. Climate Report Says Put a High Price ...
2018-10-09,2882.510010,2894.830078,2874.270020,2880.340088,2880.340088,3.520500e+09,-0.001419,-9.479757,0.000000,20.560058,Kanye West Expected to Visit Trump at the Whit...
2018-10-10,2873.899902,2874.020020,2784.860107,2785.679932,2785.679932,4.501250e+09,-0.033416,-17.312894,0.000000,95.479981,Learning With: ‘Banksy Painting Self-Destructs...
2018-10-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Corrections: October 11, 2018Khashoggi’s Disap..."

# Export new data as a csv file

In [7]:
data.to_hdf("data.h5", 'data')

/home/bf/anaconda3/envs/dasc/lib/python3.6/site-packages/pandas/core/generic.py:1996: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block1_values] [items->['News']]

  return pytables.to_hdf(path_or_buf, key, self, **kwargs)